# This file was automatically generated by fetch.py
from pathlib import Path


def __getattr__(name):
    with open(Path(__file__).parent / (name.lower() + ".txt"), "r") as file:
        return file.read().strip()
